### PR TITLE
ci: use cargo-hack and build all valid feature combos

### PR DESCRIPTION
**Pull request by a10y**
I've added [cargo-hack](https://github.com/taiki-e/cargo-hack) which seems extremely popular, e.g. futures-util uses it for their CI builds. It actually will go build each of your workspace projects individually.

I've setup a build matrix that uses cargo-hack to run builds with all valid feature combos we care about:

* default
* all-features
* wasm32
* tokio
* compio
* tokio+compio

### CODE REVIEW

**Comment by a10y** [comment]
Seems like Actions is erroring, will fix tomorrow

**Comment by AdamGS** [comment]
my 2c - I think the default should be tokio on the **current** runtime, with no dispatching/spinning out new threads, allowing users to control that aspect of the overall program (for example - in cases where they already do their Vortex IO on a dedicated runtime).

**Comment by a10y** [comment]
So like a block_in_place?

**Comment by a10y** [comment]
I think I see what you're saying. You check for the presence of an active runtime Handle and if so spawn the task in a local set there. Let me try changing this around and see how that works.

**Comment by a10y** [comment]
@AdamGS I've filed an issue to address revisiting IoDispatcher: https://github.com/spiraldb/vortex/issues/1670.

My primary goals with this PR are

- Improve our CI to test all valid feature combos
- Make current `vortex-io` build successfully with only default features

**Review by AdamGS — APPROVED** [review]

**Pull request merged**
