### PR TITLE
Update croaring-sys to 4.1.4 and remove workarounds for croaring/660

### PR DESCRIPTION
**Pull request by robert3005**
Since we don't have a direct dependency on croaring-sys I manually run cargo update to update all locked dependencies to latest in range

### CODE REVIEW

**Review by lwwmanning — CHANGES_REQUESTED** [review]
Since we know it doesn't work for croaring versions < 4.1.4, we should update our workspace-level croaring dep to 2.1.0 (which sets 4.1.4 as the min version)

**Comment by robert3005** [comment]
ah, that's why it didn't automatically bump croaring-sys

**Comment by robert3005** [comment]
Nope, croaring-rs 2.1.0 doesn't set the min version. Can put an explicit bound on croaring-sys

**Comment by robert3005** [comment]
Hm, no it should but then cargo is silly

**Comment by lwwmanning** [comment]
Screenshot 2024-09-20 at 12 49 00

well that's because they're being silly, the readme from the 2.1.0 release states a requirement for 4.1.4

**Comment by robert3005** [comment]
I think since we have an existing dependency on croaring-sys, i.e. 4.1.1 that satisfies ~4.1.4 if I understand this correctly

**Review by lwwmanning — APPROVED** [review]
derp

**Pull request merged**
