### PR TITLE
A test that shows the writer is not thread safe

### PR DESCRIPTION
**Pull request by joseph-isaacs**
Do you think we want to make this thread safe (send)?

### CODE REVIEW

**Comment by gatesn** [comment]
Why does write task need to be Send (which != thread safe)?

**Comment by joseph-isaacs** [comment]
So we can use it in a tokio::spawn

**Comment by joseph-isaacs** [comment]
Otherwise we get this error:

```
error[E0277]: `(dyn vortex_file::write::metadata_accumulators::MetadataAccumulator + 'static)` cannot be sent between threads safely
   --> ....
    |
37  |       let file_format_metadata = py_block_on(
    |                                  ----------- required by a bound introduced by this call
38  |           py,
39  | /         spfs::table::write_table(
40  | |             context,
41  | |             &url,
42  | |             token.map(Arc::from),
...   |
48  | |             properties.unwrap_or_default().config,
49  | |         ),
    | |_________^ `(dyn vortex_file::write::metadata_accumulators::MetadataAccumulator + 'static)` cannot be sent between threads safely
```

**Comment by joseph-isaacs** [comment]
Surely we must support this use case?

**Comment by gatesn** [comment]
Possibly? But why would we spawn a write operation?

**Comment by gatesn** [comment]
Ohhhhh sorry I mis-read your thing

**Comment by joseph-isaacs** [comment]
I will think we should make this send

**Comment by lwwmanning** [comment]
closing in favor of #1479

**Pull request closed without merging**
