### PR TITLE
feat: increase dict decompression throughput

### PR DESCRIPTION
**Pull request by danking**
If we are canonicalizing the dictionary, we will likely canonicalize all the values. For formats like bitpacking this substantially improves throughput. In particular, we spend a lot of time preparing the indices for chunked decoding and then pplying the patches.

### CODE REVIEW

**Comment by a10y** [comment]
I wonder if this is more general than dicts, and if so, if it might be worth finding a way to cache the results of decoding that happens in compute fns

**Comment by robert3005** [comment]
Is this because there’s no take implementation or is there something genuinely different about canonical values? I would bias towards 1. Finding more general rule about when to canonicalize and when to not 2. Implementing more compute functions 3. Have a way to reuse canonicalization results

**Comment by danking** [comment]
Heh, across the board improvement to decompression:

cc: @lwwmanning 

| Benchmark suite | Current: 699a7a9baa1b1846c61ae0833ab5cd2cb3ce188c | Previous: 8d9f62064c63350bccf18be76b308f435433c0a1 | Ratio |
|-|-|-|-|
| `taxi` | `383191606.45` ns | `461548978.45` ns | `0.83` |
| `AirlineSentiment` | `38097.31788964077` ns | `38126.30644984732` ns | `1.00` |
| `Arade` | `720931444.5` ns | `758913896.8` ns | `0.95` |
| `Bimbo` | `2933064229.8` ns | `6676621953.2` ns | `0.44` |
| `CMSprovider` | `7279172734.4` ns | `15740825404.6` ns | `0.46` |
| `Euro2016` | `350970748.25` ns | `443450569.95` ns | `0.79` |
| `Food` | `300631666.5` ns | `617245638.5` ns | `0.49` |
| `HashTags` | `605084068` ns | `1242753128.7` ns | `0.49` |
| `TPC-H l_comment chunked` | `90496755.31998016` ns | `101999063.95884919` ns | `0.89` |

**Comment by danking** [comment]
TPC-H is a bit all over the place except Q19 which is notably faster.

**Comment by robert3005** [comment]
Which take methods are we missing here?

**Comment by lwwmanning** [comment]
We aren't missing any! But dict canonicalization ends up decompressing the whole codes array (but potentially as lots of unpack_singles)

**Comment by robert3005** [comment]
I think this could be a take optimization, i.e. if you are taking with bigger array than the source array you could just canonicalize

**Comment by danking** [comment]
@robert3005 @a10y 

> I wonder if this is more general than dicts, and if so, if it might be worth finding a way to cache the results of decoding that happens in compute fns

> Is this because there’s no take implementation or is there something genuinely different about canonical values? I would bias towards 1. Finding more general rule about when to canonicalize and when to not 2. Implementing more compute functions 3. Have a way to reuse canonicalization results

BitPackedArray has a `take` implementation but, experimentally, it is slow when the number of indices is much larger than the number of values. I've attached the speed scope for `origin/develop`. My read is that there are a few issues:
1. Grouping indices by their 1024-element chunk is oddly expensive. Itertools::chunk_by seems to consume a lot of cycles.
2. `do_patch_for_take_primitive` is dominated by hash map construction. 
3. Converting a Vec<bool> into a BooleanBuffer is oddly expensive.

This PR avoids 1 & 2. I think the big generalizable lesson is: when indices vastly outnumber values, rearrange the values for simple indexing rather than munging the indices. We trade operations on 10s of thousands of values for operations on 100s of values.

I'm working on something for 3 now.

---

Zoom in on `criterion::bencher::Bencher<M>::iter_batched`. Everything else is set-up for the decompression benchmark which happens to be very fast.

[develop-bimbo-decompress.speedscope.json](https://github.com/user-attachments/files/17369466/develop-bimbo-decompress.speedscope.json)

**Comment by danking** [comment]
@robert3005 to your point, I can add a switch to `BitPackedArray`'s `take` instead. Let me try that.

**Comment by danking** [comment]
Running benchmarks here: https://github.com/spiraldb/vortex/pull/1033

**Comment by danking** [comment]
#1033 is strictly worse than #1036, so we closed #1033. Neither #1033 nor #1036 recapitulate the gains of this PR, #1032.

**Comment by robert3005** [comment]
eh because unless you are able to store the result of canonicalization everything else does more work

**Review by lwwmanning — APPROVED** [review]

**Comment by robert3005** [comment]
This pr seems weird, the weirdness is that there's some better order of operations that you can perform and if you don't follow them you get worse performance. What kind of change can we make so we don't have to think about one off changes like this?

**Pull request merged**
