### PR TITLE
feat: specialized IntoCanonical for DictArray utf8/binary

### LINKED ISSUE #1041: Re-evaluate values canonicalization in `DictArray::into_canonical`
In #1032 we always canonicalize the dictionary, since that is optimal under the assumption that `codes.len() >= values.len()`. This is always true in the absence of shared dictionaries.

After we address #252, we may want to take a more nuanced approach. In particular, a #1038 may be a better approach

### PR DESCRIPTION
**Pull request by a10y**
Fixes #1041 

Change the IntoCanonical implementation for DictArray to do canonicalize-then-take for stringy things, take-then-canonicalize for everything else.

It is always the case for strings that canonicalize-then-take will be faster, regardless of the compression of the values array.

Overrides #1136

### CODE REVIEW

**Review by lwwmanning — APPROVED** [review]

**Comment by lwwmanning** [comment]
benchmarks are mostly within tolerances, but CMS provider decompression got 11% slower

Screenshot 2024-10-28 at 14 25 35

**Comment by a10y** [comment]
All of the TPCH queries seem unaffected so think this is good to go

**Comment by a10y** [comment]
Missed your comment @lwwmanning , the slowdown for CMSprovider is a bit surprising. It has a few integer columns that maybe dict encode but is mostly strings, which should be unaffected by this change

**Comment by lwwmanning** [comment]
> Missed your comment @lwwmanning , the slowdown for CMSprovider is a bit surprising. It has a few integer columns that maybe dict encode but is mostly strings, which should be unaffected by this change

@a10y yeah, there's maybe something there, but I tend to agree with Nick's assessment that we should dig into it / fix that lower down

**Pull request merged**
