### PR TITLE
chore: simplify StatsSet

### PR DESCRIPTION
**Pull request by a10y**
Changed Option<Scalar> -> Scalar. If there's a reason why it was Option, I couldn't find it.

There are a lot of methods, regrouped them into blocks based on function. Also added some docstrings.

Add a non-consuming `iter` for iterating over the StatsSet values, so that you can use it without `.clone()` first.

### CODE REVIEW

**Comment by a10y** [comment]
My ulterior motive is that I want to display stats in my WASM app

**Comment by robert3005** [comment]
Things were optional to signify that stat was computed but unsupported

**Comment by a10y** [comment]
I couldn't find anywhere that you could actually insert a `None` in for the Scalar

**Comment by robert3005** [comment]
I guess the implementation will have to know that it doesn't support the stat and could short circuit there.

**Review by robert3005 — APPROVED** [review]

**Pull request merged**
