### PR TITLE
feat: Add uncompressed size stat for Vortex/Datafusion

### PR DESCRIPTION
**Pull request by AdamGS**
As a followup to #1455 as @robert3005 noted.

### CODE REVIEW

**Comment by AdamGS** [comment]
A bit surprised by the performance regressions, I'll take a deeper look next week.

**Comment by gatesn** [comment]
I don't think this should be a statistic.

Perhaps a compute function, or just something like nbytes.

**Review by lwwmanning — CHANGES_REQUESTED** [review]
There's already `Stat::UncompressedSizeInBytes` that we compute before compressing! Don't need to decompress/recalculate

**Comment by lwwmanning** [comment]
See #1315

**Comment by gatesn** [comment]
It just doesn't seem like it fits the definition of a statistics, because I can compute it in constant time. So why do we need to store it?

**Comment by robert3005** [comment]
@gatesn we can remove it as a statistic if it's computable in constant time. I don't quite know how to do it but happy to review a pr. Alternatively it can be only a feature of file format and not in memory arrays if you think it shouldn't be a statistic

**Review by lwwmanning — APPROVED** [review]

**Pull request merged**
