### PR TITLE
feat: if indices >> values, take decompresses bitpacked array

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
too conservative it seems

| Benchmark suite | Current: 83b254e7b50b5af4b039ea3a54120424f22152fb | Previous: 8d9f62064c63350bccf18be76b308f435433c0a1 | Ratio |
|-|-|-|-|
| taxi | 1309246396.7 ns (3004334.846250057) | 1221461368.8 ns (10559798.950000048) | 1.07|
| AirlineSentiment | 386379.73649448476 ns (185.3331912244612) | 389136.55839532666 ns (775.4222039520973) | 0.99|
| Arade | 2011922451.2 ns (2129750.0812500715) | 2006834037.7 ns (4987853.808750033) | 1.00|
| Bimbo | 11857366605.3 ns (11162571.80000019) | 10781648046 ns (22571813.001249313) | 1.10|
| CMSprovider | 10922789186.4 ns (10555885.757499695) | 10844829973.3 ns (17310398.923749924) | 1.01|
| Euro2016 | 2240373052.2 ns (1141159.2350001335) | 2266910624.2 ns (3362859.138749838) | 0.99|
| Food | 1069673590.7 ns (1126111.8799999356) | 1031097304.4 ns (977250.4737499952) | 1.04|
| HashTags | 2398213899.7 ns (1364190.649999857) | 2422585450 ns (7450602.807499886) | 0.99|
| TPC-H l_comment chunked without fsst | 210401618.1 ns (204169.31458333135) | 209339922.9 ns (270522.82958331704) | 1.01|
| TPC-H l_comment chunked | 784954222.1 ns (742868.7274999619) | 791612419.7 ns (973609.0500000119) | 0.99|
| TPC-H l_comment canonical | 784502005.85 ns (404727.78125) | 785626160.5 ns (540480.7443749905) | 1.00|

**Comment by danking** [comment]
Decompress summary

| Benchmark suite | Current: 05a88186e9e0c2aff77a4bbae049c417daa2b1f7 | Previous: 8d9f62064c63350bccf18be76b308f435433c0a1 | Ratio |
|-|-|-|-|
| `taxi` | `367768104.45` ns  | `461548978.45` ns  | `0.80` |
| `AirlineSentiment` | `37129.004122730104` ns  | `38126.30644984732` ns  | `0.97` |
| `Arade` | `759255725.1` ns  | `758913896.8` ns  | `1.00` |
| `Bimbo` | `3301392141.4` ns  | `6676621953.2` ns  | `0.49` |
| `CMSprovider` | `9441595159.1` ns  | `15740825404.6` ns  | `0.60` |
| `Euro2016` | `348445797.3` ns  | `443450569.95` ns  | `0.79` |
| `Food` | `350215111.75` ns  | `617245638.5` ns  | `0.57` |
| `HashTags` | `770813708.2` ns  | `1242753128.7` ns  | `0.62` |
| `TPC-H l_comment chunked` | `105179540.86690477` ns  | `101999063.95884919` ns  | `1.03` |

**Comment by lwwmanning** [comment]
yeah, benchmarking on #1036 seems to indicate that we should be even more aggressive: https://github.com/spiraldb/vortex/pull/1036#issuecomment-2412574717

**Comment by lwwmanning** [comment]
closing in favor of #1036

**Pull request closed without merging**
