### PR TITLE
chore: port random access benchmark to layouts

### PR DESCRIPTION
**Pull request by danking**
develop was a643065102f24e1feeccb324ceeb0245a7405be6
layouts was this PR: 6dc6c53a477a67231a3bc425459c84f10dd8f0d1
```
# critcmp develop layouts
group                                     develop                                layouts
-----                                     -------                                -------
random-access/parquet-tokio-local-disk    1.01     94.0±0.44ms        ? ?/sec    1.00     93.3±0.62ms        ? ?/sec
random-access/vortex-local-fs             1.00   381.3±10.78µs        ? ?/sec    34.91    13.3±0.13ms        ? ?/sec
random-access/vortex-tokio-local-disk     1.00   349.5±12.64µs        ? ?/sec    29.46    10.3±0.14ms        ? ?/sec
```

### CODE REVIEW

**Comment by robert3005** [comment]
interesting, I guess now we have to make it faster again

**Comment by danking** [comment]
My best guess is that we've traded a take for a filter and filter is apparently very slow.

**Comment by robert3005** [comment]
Yeah, we don't have a switch to do a take for very sparse mask

**Comment by robert3005** [comment]
there's a bunch of improvements we can make to our file format but now this is a real metric #1248 and #1247

**Review by robert3005 — APPROVED** [review]

**Pull request merged**
