### PR TITLE
Use array len as denominator for selectivity

### PR DESCRIPTION
**Pull request by robert3005**
True range is too expensive of a metric to calculate given current apis

### CODE REVIEW

**Comment by robert3005** [comment]
I have found this while spot checking profiles - in q19 computing true range was 30% of all our compute time

**Comment by gatesn** [comment]
I can maybe believe it, but the benchmark run doesn't agree with you?

**Comment by robert3005** [comment]
It’s overall 5% better or am I looking at wrong numbers?

**Review by lwwmanning — APPROVED** [review]

**Comment by danking** [comment]
The q19 row didn't show an improvement which seems suspicious given the profile

**Comment by robert3005** [comment]
Yeah so I have run this on top of #1466 on my laptop and that was an improvement. I imagine our ci machines would produce a different profile. Could also be that this is bigger improvement with #1466 that it is standalone

**Pull request merged**
