### PR TITLE
feat: use VarBinView as the new canonical string type

### PR DESCRIPTION
**Pull request by a10y**
Supplants #476.

VarBinView is the new canonical representation for string types across the repo. There are still many places that natively use VarBin arrays internally, we can replace those over time.

* `Canonical::VarBin` -> `Canonical::VarBinView`
* FSSTArray, ConstArray, DictArray now all canonicalize into VarBinView
* Updated the TPC-H setup to use Utf8View schemas

### CODE REVIEW

**Comment by robert3005** [comment]
I think https://github.com/apache/arrow-rs/issues/6366 is going to make python tests fail

**Comment by a10y** [comment]
Yea, even bumping PyArrow from 15 -> 17 (latest) did not seem to change that

**Comment by a10y** [comment]
Blocked on https://github.com/apache/arrow-rs/pull/6368

**Comment by a10y** [comment]
Converting back to draft while this is blocked

**Comment by robert3005** [comment]
I think with arrow 53.1.0 this is no longer blocked

**Comment by a10y** [comment]
image

Time for a take3 PR 🥲

**Comment by robert3005** [comment]
git cli is a lot smarter than github ui but probably still hard

**Pull request closed without merging**
