### PR TITLE
two digit queries

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
@AdamGS this makes it easier to filter to single digit queries a la `q-02` without triggering `q-20`, `q-21`, etc.

**Review by a10y — APPROVED** [review]

**Comment by a10y** [comment]
fwiw what i usually do is use a filter of `q2/`

**Comment by danking** [comment]
Meaning you append a slash to the query name? a la `clickbench/q11/`?

**Comment by a10y** [comment]
e.g. `cargo bench --bench tpch -- "q1/"`

**Comment by AdamGS** [comment]
lets merge it, `bench test` fails for unrelated reasons and I'll fix that in the original PR.

**Comment by danking** [comment]
Ah I think this is because the tpch queries are named differently. I suppose it would be nice for us to have `--bench clickbench -- q2/vortex` as well as `q2/parquet` so that we can compare executions on the same machine

**Pull request merged**
