### PR TITLE
REE infers length from ends array

### LINKED ISSUE #19: REEArray should infer length from values and not take it in constructor
Right now this is necessary since not all arrays implement scalar_at

### PR DESCRIPTION
**Pull request by robert3005**
fixes #19

### CODE REVIEW

**Comment by robert3005** [comment]
Will reopen this later, need to bring back some more scalar_at impls

**Review by lwwmanning — APPROVED** [review]

**Comment by lwwmanning** [comment]
possible now that #160 has merged 🥳

**Comment by jdcasale** [comment]
This PR introduces a panic when running bench compress, investigating.

`RUST_BACKTRACE=1 cargo run -r --color=always --bin compress --manifest-path /Users/jcasale/fulcrum/vortex/bench-vortex/Cargo.toml `

```thread 'main' panicked at vortex-ree/src/ree.rs:41:13:
assertion `left == right` failed
  left: 1024
 right: 0
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: vortex_ree::ree::REEArray::try_new
   5: vortex_ree::compress::<impl vortex::compress::EncodingCompression for vortex_ree::ree::REEEncoding>::compress
   6: vortex::compress::find_best_compression
   7: vortex::compress::sampled_compression
   8: vortex::compress::CompressCtx::compress_array
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: core::iter::adapters::try_process
  11: vortex::compress::CompressCtx::compress_array
  12: vortex::compress::CompressCtx::compress
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  15: bench_vortex::reader::compress_parquet_to_vortex
  16: compress::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by robert3005** [comment]
@jdcasale it's #193. In cases where it throws the ends array is bitpacked and it must be bitpacked to 0 bits with patches

**Pull request merged**
