### PR TITLE
Use BufResult

### PR DESCRIPTION
**Pull request by a10y**
Currently our async IO traits have methods that receive an owned buffer (in the form of `BytesMut`) and return an `io::Result<BytesMut>` which gives the buffer back at the end.

The trouble is, in the case of an error the buffer will leak. This is not a problem yet since we currently allocate a fresh buffer for every IO operation, but as we move toward buffer pools and completion-based IO operations, we don't want to leak these buffers when IO errors occur.

This PR makes a new `BufResult<T>` which is just a `(io::Result<T>, BytesMut)` to ensure that you always return ownership of the buffer to the caller even in the event of IO failures.

Currently this doesn't change any behavior, but when we swtich to pre-allocated buffers and IO operations using those, it will matter.

### CODE REVIEW

**Comment by a10y** [comment]
I'll put this back to draft so it can be sequenced after #1124

**Comment by a10y** [comment]
Note to self: double-check compio's approach and see if that's better: https://github.com/compio-rs/compio/blob/master/compio-buf/src/buf_result.rs

**Comment by robert3005** [comment]
the more code like that I write the more I prefer an explicit struct instead of anonymous tuple

**Comment by a10y** [comment]
This is going to be supplanted by some other work

**Pull request closed without merging**
