### PR TITLE
feat: faster fast lanes

### PR DESCRIPTION
**Pull request by danking**
FFffast

### CODE REVIEW

**Comment by a10y** [comment]
So if you look at the lockfile, the actual version has been on 1.8 since #890. I think this is because by default Rust version specifiers have an implicit `^` in front of them, so it will auto-resolve patch version bumps ([see this](https://stackoverflow.com/questions/45224563/how-to-specify-the-exact-version-of-a-dependency)).

What might be better is to change the version spec to `0.1`

**Comment by danking** [comment]
so much for my cheap wins! hmm; I'm not sure what's best to be honest but the implicit ^ seems odd

**Comment by danking** [comment]
I guess if you're a real rustacean this is obvious though

**Comment by a10y** [comment]
Tbh it was not obvious, I always forget about this behavior, my spidey sense went off when the PR didn't trigger a change to the lockfile

**Pull request closed without merging**
