### PR TITLE
feat: print diagnostic for function implementations

### PR DESCRIPTION
**Pull request by robert3005**
This can be further simplified with use of proc macros

### CODE REVIEW

**Comment by robert3005** [comment]
`cargo run --bin notimplemented`

**Comment by lwwmanning** [comment]
Can you put it in xtask instead of bench-vortex?

**Comment by robert3005** [comment]
I cannot since I need to depend on all encodings

**Comment by robert3005** [comment]
I can make a separate package

**Comment by lwwmanning** [comment]
meh, it's fine

**Review by lwwmanning — APPROVED** [review]

**Pull request merged**
