### PR TITLE
chore: use PrimitiveArray::patch in bitpacking take

### LINKED ISSUE #213: Unify logic for owned PrimitiveArray patching in bitpacking
Right now bitunpacking and take use two different code paths for applying patches but there's no reason why they couldn't

### PR DESCRIPTION
**Pull request by danking**
Resolves #213 (I think!).

### CODE REVIEW

**Comment by lwwmanning** [comment]
would be good to run `cargo bench --bench bitpacking_take` on this branch vs develop just to confirm no regression, but lgtm

**Review by lwwmanning — APPROVED** [review]

**Comment by danking** [comment]
Hmm. there is a real slowdown:
```
group                                      develop                                pr
-----                                      -------                                --
patched_take_10K_adversarial               1.08    101.9±4.15µs        ? ?/sec    1.00     94.6±7.05µs        ? ?/sec
patched_take_10K_contiguous_not_patches    1.00     45.5±2.82µs        ? ?/sec    1.25     56.8±3.00µs        ? ?/sec
patched_take_10K_contiguous_patches        1.00     82.4±2.93µs        ? ?/sec    1.30   106.7±14.22µs        ? ?/sec
patched_take_10K_random                    1.00    157.2±6.15µs        ? ?/sec    1.03    161.5±6.88µs        ? ?/sec
patched_take_10_contiguous                 1.01    942.3±7.77ns        ? ?/sec    1.00   932.6±18.96ns        ? ?/sec
patched_take_10_stratified                 1.00    896.2±4.57ns        ? ?/sec    1.02   910.1±20.52ns        ? ?/sec
patched_take_200K_dispersed                1.00   496.6±50.84µs        ? ?/sec    1.02   506.6±41.16µs        ? ?/sec
patched_take_200K_first_chunk_only         1.08   388.0±25.74µs        ? ?/sec    1.00   360.3±19.99µs        ? ?/sec
take_10K_contiguous                        1.01     11.3±0.04µs        ? ?/sec    1.00     11.2±0.07µs        ? ?/sec
take_10K_random                            1.00     58.9±0.16µs        ? ?/sec    1.05     61.6±0.42µs        ? ?/sec
take_10_contiguous                         1.09    401.8±8.34ns        ? ?/sec    1.00    369.7±8.71ns        ? ?/sec
take_10_stratified                         1.02    365.1±2.30ns        ? ?/sec    1.00    356.9±3.47ns        ? ?/sec
take_200K_dispersed                        1.00    421.7±6.07µs        ? ?/sec    1.02   431.1±19.55µs        ? ?/sec
take_200K_first_chunk_only                 1.02   324.7±18.05µs        ? ?/sec    1.00   318.9±15.96µs        ? ?/sec
```

**Comment by danking** [comment]
The profiles lack any clear issues. I ran `take` 1,000 times in a loop and also ran the pull request, then develop, then the pull request again.

```
group                                      develop               pr                      pr2
-----                                      -------               --                      ---
patched_take_10K_contiguous_not_patches    1.00     44.1±0.19ms  1.03     45.3±0.53ms    1.01     44.5±0.67ms
patched_take_10K_contiguous_patches        1.02     82.7±3.97ms  1.07     86.7±3.64ms    1.00     81.0±1.42ms
```
```
diff --git a/encodings/fastlanes/benches/bitpacking_take.rs b/encodings/fastlanes/benches/bitpacking_take.rs
index 6706c9564..caabb2431 100644
--- a/encodings/fastlanes/benches/bitpacking_take.rs
+++ b/encodings/fastlanes/benches/bitpacking_take.rs
@@ -114,7 +114,11 @@ fn bench_patched_take(c: &mut Criterion) {
         .collect_vec()
         .into();
     c.bench_function("patched_take_10K_contiguous_not_patches", |b| {
-        b.iter(|| black_box(take(packed.as_ref(), not_patch_indices.as_ref()).unwrap()));
+        b.iter(|| {
+            for _ in 0..1000 {
+                black_box(take(packed.as_ref(), not_patch_indices.as_ref()).unwrap());
+            }
+        });
     });
 
     let patch_indices: PrimitiveArray = (big_base2..big_base2 + num_exceptions)
@@ -123,7 +127,11 @@ fn bench_patched_take(c: &mut Criterion) {
         .collect_vec()
         .into();
     c.bench_function("patched_take_10K_contiguous_patches", |b| {
-        b.iter(|| black_box(take(packed.as_ref(), patch_indices.as_ref()).unwrap()));
+        b.iter(|| {
+            for _ in 0..1000 {
+                black_box(take(packed.as_ref(), patch_indices.as_ref()).unwrap());
+            }
+        });
     });
 
     let lots_of_indices: PrimitiveArray = (0..200_000)
```

**Comment by danking** [comment]
For posterity, here's why this PR appeared to slow things down slightly. The latest changes actually notably reduce take time when the number of patches is large.

This PR modified `BitPackedEncoding::take` to use `PrimitiveArray::patch(Patches)` instead of implementing patching itself. `PrimitiveArray::patch`, although it took an owned `Patches`, called `indices()` and `values()` and then `clone`d them, thus incrementing the reference count to the underlying buffers. When we called `into_maybe_null_slice`, we (always) forced a copy of these buffers. This PR avoids that by using `into_parts` to get the indices and value of a `Patches`.

Critcmp shows `patched_take_10K_contiguous_not_patches` as a little slower, but if you look carefully the error bands are overlapping (develop could be as high as 56, pr could be as low as 53). In both develop and this PR, we call `patches.take(&indices.to_array())`. In both cases, for this test, `take` should return `None` and we should skip the part of the code that differs.
```
group                                      develop               pr                  
-----                                      -------               --
patched_take_10K_adversarial               1.13    101.8±3.21µs  1.00     90.2±7.68µs
patched_take_10K_contiguous_not_patches    1.00     50.0±6.08µs  1.07     53.7±3.79µs
patched_take_10K_contiguous_patches        1.02     98.3±2.48µs  1.00     96.1±6.77µs
patched_take_10K_random                    1.02    153.0±5.64µs  1.00    150.3±4.64µs
patched_take_10_contiguous                 1.06   983.4±18.63ns  1.00   928.3±17.56ns
patched_take_10_stratified                 1.00    919.9±7.37ns  1.01   928.8±10.46ns
patched_take_200K_dispersed                1.22   480.9±24.74µs  1.00   394.4±14.78µs
patched_take_200K_first_chunk_only         1.25   377.9±32.04µs  1.00   302.5±19.84µs
take_10K_contiguous                        1.03     11.3±0.02µs  1.00     11.0±0.17µs
take_10K_random                            1.00     58.9±0.27µs  1.00     59.0±0.49µs
take_10_contiguous                         1.00    396.0±8.07ns  1.02    405.1±4.54ns
take_10_stratified                         1.06   400.2±12.41ns  1.00   378.6±10.37ns
take_200K_dispersed                        1.25   435.3±22.05µs  1.00    348.7±7.17µs
take_200K_first_chunk_only                 1.32   321.2±12.22µs  1.00    242.6±6.01µs
```

**Pull request merged**
