### PR TITLE
Pass additional encodings to TableProvider instead of context

### PR DESCRIPTION
**Pull request by robert3005**

### CODE REVIEW

**Comment by robert3005** [comment]
@a10y

**Comment by a10y** [comment]
what i was getting at was, wouldn't it make more sense to just apply the SamplingCompressor encodings by default?

**Comment by robert3005** [comment]
hm, the dependency chain is a bit annoying. vortex-datafusion doesn't depend on the compressor right now. We might say fuck it and add it or keep it as is in this pr

**Comment by a10y** [comment]
ah, you're right. yea i was hoping there was a way to zero-args load a vortex file for the 99% of cases where that applies, maybe something to change in the future.

i think passing in an explicit context is fine for now in that case, so maybe don't need this PR

**Comment by robert3005** [comment]
I think we can provide some top level crate that aggregates all the available encodings and we can put a list there but still passing things around is weird

**Pull request closed without merging**
