### PR TITLE
Benchmarks to shell out to DuckDB

### PR DESCRIPTION
**Pull request by gatesn**
No point spending all our time compiling it

### CODE REVIEW

**Review by jdcasale — COMMENTED** [review]
Will defer to @robert3005 on this, but I think it’s fine. If we end up using ducksb for anything else this will get gross though. 

Should probably add a README note so that someone running these benchmarks without duckdb preinstalled doesn’t have to spend time scratching their head over it.

**Comment by gatesn** [comment]
How do you mean it will get gross?

**Comment by jdcasale** [comment]
> How do you mean it will get gross?

Mostly an aesthetic aversion to shelling out to an unmanaged binary when we don't have to. It's not a big deal because this is just benchmark code, and I think you're right that the better compile time outweighs this.

Worst case (probably won't happen) though we end up using this for other parts of the benchmarks and end up in a scenario where some duckdb version between environments gives us confusing results that differ across machines.

**Review by jdcasale — APPROVED** [review]
Ehh on second thought nvm — Rob can revert it if he cares next week

**Comment by robert3005** [comment]
Shelling out is fine. I went with the simplest solution. You need to probably add duck db to bench ci, though we haven’t used it in a while

**Review by robert3005 — APPROVED** [review]

**Pull request merged**
