### PR TITLE
fix: rely on ScalarValue Display in Scalar Display

### PR DESCRIPTION
**Pull request by danking**
Curious for your thoughts on Utf8 and Buffer. It feels a little wrong to change them to truncate by default? I think I really want two kinds of `Display`, one that's lossless and one that's lossy and meant to be "small".

### CODE REVIEW

**Comment by robert3005** [comment]
I think we can add a a verbose display to scalars that wraps the scalar and has non truncating display? We could abstract it behind a new kind of Display trait (like datafusion with DisplayAs)

**Comment by robert3005** [comment]
I think having a verbose wrapper would be enough though

**Review by robert3005 — APPROVED** [review]
We should as a followup make utf8/binary have shortened displays as well (with option to print the whole thing)

**Comment by danking** [comment]
Okay! I'll sort something out for a verbose display and a normal one.

**Pull request merged**
